var bill = document.querySelector('#bill');
var number_of_people = document.querySelector('#number_of_people');
var tips = document.querySelectorAll('input[type="radio"]');
var custom = document.querySelector('#custom');
var total = document.querySelector('#total');
var tip_amount = document.querySelector('#tip_amount');
var reset = document.querySelector('#reset');
var alert_bill = document.querySelector('#alert_bill');
var alert_tip = document.querySelector('#alert_tip');
var alert_people_number = document.querySelector('#alert_people_number');
console.log(bill, " call");
console.log(tips);
